# -*- coding: utf-8 -*-
"""The Self-Pruning Neural Network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QswYUVrjyq6VooNyxl5CfnYJXfRDcM99

Imports & Setup
```
# This is formatted as code
```
"""

# MODULE 1: Imports
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

"""Load CIFAR-10"""

# MODULE 2: Dataset

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

train_dataset = datasets.CIFAR10(root="./data", train=True, download=True, transform=transform)
test_dataset = datasets.CIFAR10(root="./data", train=False, download=True, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=128, shuffle=False)

"""PrunableLinear (CORE)"""

# MODULE 3: Prunable Linear Layer

class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()

        self.weight = nn.Parameter(torch.randn(out_features, in_features) * 0.01)
        self.bias = nn.Parameter(torch.zeros(out_features))

        # IMPORTANT: gate scores
        self.gate_scores = nn.Parameter(torch.randn(out_features, in_features) - 2)

    def forward(self, x):
        gates = torch.sigmoid(self.gate_scores)
        pruned_weights = self.weight * gates
        return F.linear(x, pruned_weights, self.bias)

"""Model"""

# MODULE 4: Neural Network

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = PrunableLinear(32*32*3, 512)
        self.fc2 = PrunableLinear(512, 256)
        self.fc3 = PrunableLinear(256, 10)

    def forward(self, x):
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

"""Sparsity Loss"""

# MODULE 5: Sparsity Loss

def compute_sparsity_loss(model):
    loss = 0
    for layer in model.modules():
        if isinstance(layer, PrunableLinear):
            gates = torch.sigmoid(layer.gate_scores)
            loss += gates.sum()
    return loss

"""Training Function"""

# MODULE 6: Training

def train(model, loader, optimizer, lambda_val):
    model.train()
    total_loss = 0

    for data, target in loader:
        data, target = data.to(device), target.to(device)

        optimizer.zero_grad()

        output = model(data)
        classification_loss = F.cross_entropy(output, target)

        sparsity_loss = compute_sparsity_loss(model)

        loss = classification_loss + lambda_val * sparsity_loss

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(loader)

"""Test Function"""

# MODULE 7: Evaluation

def test(model, loader):
    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for data, target in loader:
            data, target = data.to(device), target.to(device)

            output = model(data)
            pred = output.argmax(dim=1)

            correct += (pred == target).sum().item()
            total += target.size(0)

    return 100 * correct / total

"""Sparsity Calculation"""

# MODULE 8: Sparsity %

def calculate_sparsity(model, threshold = 0.05):
    total = 0
    zero = 0

    for layer in model.modules():
        if isinstance(layer, PrunableLinear):
            gates = torch.sigmoid(layer.gate_scores)

            total += gates.numel()
            zero += (gates < threshold).sum().item()

    return 100 * zero / total

"""Train with Different λ"""

lambdas = [0.001, 0.01, 0.1]
results = []

for lambda_val in lambdas:
    print(f"\nTraining with lambda = {lambda_val}")

    model = Net().to(device)
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    for epoch in range(10):
        loss = train(model, train_loader, optimizer, lambda_val)

    acc = test(model, test_loader)
    sparsity = calculate_sparsity(model)

    print(f"Accuracy: {acc:.2f}%")
    print(f"Sparsity: {sparsity:.2f}%")

    # ✅ THIS LINE IS CRITICAL
    results.append((lambda_val, acc, sparsity))

"""Plot Gate Distribution"""

# MODULE 10: Plot

all_gates = []

for layer in model.modules():
    if isinstance(layer, PrunableLinear):
        gates = torch.sigmoid(layer.gate_scores).detach().cpu().numpy()
        all_gates.extend(gates.flatten())

plt.hist(all_gates, bins=50)
plt.title("Gate Distribution")
plt.xlabel("Gate Values")
plt.ylabel("Frequency")
plt.show()

"""Print Results Table"""

print("\nFinal Results:")
print("Lambda\tAccuracy\tSparsity")

# 🔍 Debug check
print("Results list:", results)

if len(results) == 0:
    print("⚠️ No results found. Run MODULE 9 first.")
else:
    for r in results:
        print(f"{r[0]}\t{r[1]:.2f}%\t\t{r[2]:.2f}%")